apiVersion: v1
# kubenetesリソースのshルウ意を指定する属性
kind: Pod
# リソースに付与するメタデータ
metadata:
  name: simple-echo
# リソースを定義するための属性
spec:
  containers:
  - name: nginx
    # imageはDocker Hub, ローカルどちらのイメージも使うことができる
    image: gihyodocker/nginx-proxy:latest
    env:
    - name: BACKEND_HOST
      value: localhost:8080
    ports:
    - containerPort: 80
  - name: echo
    image: gihyodocker/echo:latest
    ports:
    - containerPort: 8080
